import { Inter } from "next/font/google";
import "../globals.css";
// import Navbar from "../../components/navbar";
// import Footer from "../../components/footer";
import AboutUsTop from "../../components/aboutus/aboutustop";
import AboutUsHeroImage from "../../components/aboutus/aboutusimage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Navbar /> */}
      <AboutUsTop/>
      <AboutUsHeroImage/>
      <body className={inter.className}>{children}</body>
      {/* <Footer /> */}
    </html>
  );
}
